/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Clases.Clshistory;
import Controller.ctlhistory;
import java.sql.Timestamp;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author agos1
 */
public class RegistroHistorias extends javax.swing.JFrame {
    ctlhistory ctlhistory;
    
    LinkedList<Clshistory>historyObjectList = new LinkedList<>();

    /**
     * Creates new form RegistroHistorias
     */
    public RegistroHistorias() {
        initComponents();
        this.ctlhistory =  new ctlhistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        cbCrear = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        cbBuscar = new javax.swing.JButton();
        cbEditar = new javax.swing.JButton();
        cbEliminar = new javax.swing.JButton();
        CBtipohistoria = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtHistoria = new javax.swing.JScrollPane();
        txthistory = new javax.swing.JTextArea();
        txtidhistory = new javax.swing.JTextField();
        btBuscardescripcion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("HISTORIAS");

        jLabel2.setText("Titulo");

        jLabel3.setText("Descripcion");

        jLabel4.setText("Historia");

        cbCrear.setText("Crear");
        cbCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCrearActionPerformed(evt);
            }
        });

        jLabel5.setText("Fecha");

        cbBuscar.setText("Buscar");
        cbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBuscarActionPerformed(evt);
            }
        });

        cbEditar.setText("Editar");
        cbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEditarActionPerformed(evt);
            }
        });

        cbEliminar.setText("Eliminar");
        cbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEliminarActionPerformed(evt);
            }
        });

        CBtipohistoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "historias reales", "historias infantiles" }));

        jLabel6.setText("Autor");

        txtFecha.setToolTipText("aaaa/mm/dd");

        txthistory.setColumns(20);
        txthistory.setRows(5);
        txtHistoria.setViewportView(txthistory);

        txtidhistory.setEditable(false);

        btBuscardescripcion.setText("Buscar");
        btBuscardescripcion.setToolTipText("");
        btBuscardescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscardescripcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                    .addComponent(txtDescripcion, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btBuscardescripcion)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CBtipohistoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(txtidhistory, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbBuscar))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHistoria)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbCrear)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbEditar)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbEliminar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 76, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidhistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBtipohistoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscardescripcion))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtHistoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCrear)
                    .addComponent(cbEditar)
                    .addComponent(cbEliminar))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCrearActionPerformed
        try{
        String titulo = txtTitulo.getText();
        String descripcion_corta = txtDescripcion.getText();
        String tipo_historia = CBtipohistoria.getSelectedItem().toString();
        String historia= txthistory.getText();
        String autor = txtAutor.getText();
        String fecha = txtFecha.getText();
        
        
        
        
        if (titulo.equals("")|| descripcion_corta.equals("")||historia.equals("")||autor.equals("")||fecha.equals("")){
            JOptionPane.showMessageDialog(this, "completar todos los campos");
        }else{
            Clshistory history = new Clshistory(0, titulo, descripcion_corta, tipo_historia, historia, autor, fecha);
            ctlhistory.Createhistory(history);
            //historyObjectList.add(history);
            this.Filllist();
            this.clearhistoryfields();
            JOptionPane.showMessageDialog(this, "historia guardada correctamente");
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "revisar historia");
        }

    }//GEN-LAST:event_cbCrearActionPerformed

    private void cbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBuscarActionPerformed
        
        String titulo = txtTitulo.getText();
        Clshistory history =(Clshistory) ctlhistory.Searchhistorybytitulo(titulo, "historias reales");
        if (history == null){
            JOptionPane.showMessageDialog(this, "historia NO encontrada");
        }else{
            txtidhistory.setText(history.getId()+"");
            txtDescripcion.setText(history.getDescripcion_corta());
            CBtipohistoria.setSelectedItem(history.getTipoHistoria());
            txthistory.setText(history.getHistoria());
            txtAutor.setText(history.getAutor());
            txtFecha.setText(history.getFecha());
            txtTitulo.setText(history.getTitulo());                 
            }
        
        
        
        
        
    }//GEN-LAST:event_cbBuscarActionPerformed

    private void cbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEditarActionPerformed
        
        String titulo = txtTitulo.getText();
        String descripcion_corta = txtDescripcion.getText();
        String tipo_historia = CBtipohistoria.getSelectedItem().toString();
        String historia= txthistory.getText();
        String autor = txtAutor.getText();
        String fecha = txtFecha.getText();
        
                
        try{
            int  historyid = Integer.parseInt(txtidhistory.getText());
            Clshistory history = new Clshistory(historyid, titulo, descripcion_corta, tipo_historia, historia, autor, fecha);
            
            
            boolean response = ctlhistory.Edithistory(history);
            
            if(response){
                this.clearhistoryfields();
                JOptionPane.showMessageDialog(this, "informacion actualizada");
                }else{
                    JOptionPane.showMessageDialog(this, "error en la actualizacion");
                }
                }catch (Exception e){
                    JOptionPane.showMessageDialog(this, "cambio no guardado");
                }
                
                
            
            
            
        
       
        
        
        
    }//GEN-LAST:event_cbEditarActionPerformed

    private void cbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEliminarActionPerformed
            String titulo = txtTitulo.getText();
            
                
        try{
                                            
                boolean response = ctlhistory.Deletehistory(titulo);
            
            if(response){
                this.clearhistoryfields();
                JOptionPane.showMessageDialog(this, "informacion eliminada");
                }else{
                    JOptionPane.showMessageDialog(this, "informacion no eliminada");
                }
                }catch (Exception e){
                    JOptionPane.showMessageDialog(this, "cambio no realizado");
                }
    }//GEN-LAST:event_cbEliminarActionPerformed

    private void btBuscardescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscardescripcionActionPerformed
        String descripcion_corta = txtDescripcion.getText();
        Clshistory history1 =(Clshistory) ctlhistory.Searchhistorybydescripcion(descripcion_corta, "historias reales");
        if (history1 == null){
            JOptionPane.showMessageDialog(this, "historia NO encontrada");
        }else{
            txtidhistory.setText(history1.getId()+"");
            txtDescripcion.setText(history1.getDescripcion_corta());
            CBtipohistoria.setSelectedItem(history1.getTipoHistoria());
            txthistory.setText(history1.getHistoria());
            txtAutor.setText(history1.getAutor());
            txtFecha.setText(history1.getFecha());
            txtTitulo.setText(history1.getTitulo());                 
            }
    }//GEN-LAST:event_btBuscardescripcionActionPerformed

    private void clearhistoryfields(){
        txtTitulo.setText("");
        txtDescripcion.setText("");
        txthistory.setText("");
        txtAutor.setText("");
        txtFecha.setText("");
        CBtipohistoria.setSelectedItem(0);
    }
    
    private void Filllist(){
        DefaultListModel model = new DefaultListModel();
        int index =0;
        for (Clshistory history : historyObjectList) {
            model.add(index, history);
            index++;
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroHistorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroHistorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroHistorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroHistorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroHistorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBtipohistoria;
    private javax.swing.JButton btBuscardescripcion;
    private javax.swing.JButton cbBuscar;
    private javax.swing.JButton cbCrear;
    private javax.swing.JButton cbEditar;
    private javax.swing.JButton cbEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JScrollPane txtHistoria;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextArea txthistory;
    private javax.swing.JTextField txtidhistory;
    // End of variables declaration//GEN-END:variables
}
